routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');
Route::prefix('resource')->group(function () {
    Route::resource('country', 'CountryController');
    Route::resource('state', 'StateController');
    Route::resource('city', 'CityController');
    Route::resource('campus', 'CampusController');
    Route::resource('building', 'BuildingController');
    Route::resource('zone', 'ZoneController');
    Route::resource('area', 'AreaController');
    Route::resource('room', 'RoomController');
    Route::resource('seat', 'SeatController');
});
Auth::routes();

app/Country.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Country extends Model
{
    public function Status()
    {
        switch ($this->status) {
            case '1':
                $status = "<span class=\"badge badge-success\">Active</span>";
                break;
            case '0':
                $status = "<span class=\"badge badge-danger\">InActive</span>";
                break;
            default:
                $status = "<span class=\"badge badge-warning\">Unknown</span>";
                break;
        }
        return $status;
    }
    
    public function States()
    {
        return $this->hasMany('App\State', 'country', 'id');
    }
    
    public function Cities()
    {
        
    }
    
}

app/Http/Controllers/CountryController.php
<?php

namespace App\Http\Controllers;

use App\Country;
use Illuminate\Http\Request;

class CountryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $countries = Country::paginate(10);
        return view("resources.countries.index",['countries'=>$countries]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("resources.countries.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            "name"=>"required",
            "status"=>"int",
        ]);
        $country = new Country;
        $country->name = $request->name;
        $country->status = $request->status;
        $country->save();
        return redirect()->route('country.show',[$country->id])->with(['status'=>"New Country Created"]);

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Country  $country
     * @return \Illuminate\Http\Response
     */
    public function show(Country $country)
    {
        return view("resources.countries.show",["country"=>$country]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Country  $country
     * @return \Illuminate\Http\Response
     */
    public function edit(Country $country)
    {
        return view("resources.countries.edit",["country"=>$country]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Country  $country
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Country $country)
    {
        $request->validate([
            "name"=>"required",
            "status"=>"int",
        ]);
        $country->name = $request->name;
        $country->status = $request->status;
        $country->save();
        return redirect()->route('country.show',[$country->id])->with(['status'=>"Country Updated"]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Country  $country
     * @return \Illuminate\Http\Response
     */
    public function destroy(Country $country)
    {
        $country->delete();
        return redirect()->route('country.index')->with(['status'=>"Country Deleted"]);
    }
}

resources/views/resources/countries/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="jumbotron">
        <h3>Create new Country</h3>
        <a href="{{route('country.index')}}" class="float-right btn btn-danger">Back</a>
    </div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-6">
                <div class="card">
                    <div class="card-body">
                        <form action="{{route('country.store')}}" method="post">
                            @csrf
                            <div class="form-group">
                                <label for="precise_country_name">Name</label>
                                <input type="text" name="name" id="precise_country_name" class="form-control" value="{{old('name')}}">
                            </div>
                            <div class="form-group">
                                <label for="precise_status">Status</label>
                                <select name="status" id="precise_status" class="form-control">
                                    <option @if(old('status') == '1') selected @endif value="1">Active</option>
                                    <option @if(old('status') == '0') selected @endif value="0">InActive</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-success">Save</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/resources/countries/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="jumbotron">
        <h3>Edit {{$country->name}}</h3>
        <a href="{{route('country.show',[$country->id])}}" class="float-right btn btn-danger">Cancel</a>
    </div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-6">
                <div class="card">
                    <div class="card-body">
                        <form action="{{route('country.update',[$country->id])}}" method="post">
                            @csrf
                            <input type="hidden" name="_method" value="PUT">
                            <div class="form-group">
                                <label for="precise_country_name">Name</label>
                                <input type="text" name="name" id="precise_country_name" class="form-control" value="@if(old('name')) old('name') @else {{$country->name}}  @endif">
                            </div>
                            <div class="form-group">
                                <label for="precise_status">Status</label>
                                <select name="status" id="precise_status" class="form-control">
                                    <option @if(old('status') == '1' || $country->status == '1') selected @endif value="1">Active</option>
                                    <option @if(old('status') == '0' || $country->status == '0') selected @endif value="0">InActive</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-success">Save</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/resources/countries/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="jumbotron">
        <h3>Countries</h3>
        <a href="{{route('country.create')}}" class="float-right btn btn-info">Create</a>
    </div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-6">
                <div class="card">
                    <table class="table table-sm">
                        <thead class="table-dark">
                            <tr>
                                <th>Country</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                           @forelse ($countries as $country)
                               <tr>
                                   <th><a href="{{route('country.show',[$country->id])}}">{{$country->name}}</a></th>
                                   <th>{!!$country->Status()!!}</th>
                               </tr>
                           @empty
                               <th class="text-center" colspan="2">
                                   No countries Listed
                               </th>
                           @endforelse
                        </tbody>
                    </table>
                    <div class="card-footer">
                        {{$countries->links()}}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/resources/countries/show.blade.php
@extends('layouts.app')
@section('content')
<div class="jumbotron">
    <h3>{{$country->name}}</h3>
    {!!$country->Status()!!}
    <div class="float-right btn-group">
        <a href="{{route('country.index')}}" class="btn btn-sm btn-danger">Back</a>
        <a href="{{route('country.edit',[$country->id])}}" class="btn btn-sm btn-outline-info">Edit</a>
        <form action="{{route('country.destroy',[$country->id])}}" method="post">
            @csrf
            <input type="hidden" name="_method" value="DELETE">
            <button type="submit" class="btn btn-sm btn-outline-danger">Delete</button>
        </form>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-4">
            <div class="card">
                <table class="table table-sm">
                    <thead class="table-dark">
                        <tr>
                            <th>State</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                       @forelse ($country->States as $state)
                           <tr>
                               <th><a href="{{route('state.show',[$state->id])}}">{{$state->name}}</a></th>
                               <th>{!!$state->Status()!!}</th>
                           </tr>
                       @empty
                           <th class="text-center" colspan="2">
                               No states Listed
                           </th>
                       @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection