routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');
Route::prefix('resource')->group(function () {
    Route::resource('country', 'CountryController');
    Route::resource('state', 'StateController');
    Route::resource('city', 'CityController');
    Route::resource('campus', 'CampusController');
    Route::resource('building', 'BuildingController');
    Route::resource('zone', 'ZoneController');
    Route::resource('area', 'AreaController');
    Route::resource('room', 'RoomController');
    Route::resource('seat', 'SeatController');
});
Auth::routes();

app/State.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class State extends Model
{
    public function Status()
    {
        switch ($this->status) {
            case '1':
                $status = "<span class=\"badge badge-success\">Active</span>";
                break;
            case '0':
                $status = "<span class=\"badge badge-danger\">InActive</span>";
                break;
            default:
                $status = "<span class=\"badge badge-warning\">Unknown</span>";
                break;
        }
        return $status;
    }

    public function Country()
    {
        return $this->belongsTo('App\Country', 'country', 'id');
    }
    public function Cities()
    {
        return $this->hasMany('App\City', 'state', 'id');
    }

}

app/Http/Controllers/StateController.php
<?php

namespace App\Http\Controllers;

use App\State;
use App\Country;
use Illuminate\Http\Request;

class StateController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $states = State::paginate(10);
        return view("resources.states.index",['states'=>$states]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $countries = Country::all();
        return view("resources.states.create",['countries'=>$countries]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            "name"=>"required",
            "country"=>"int|required",
            "status"=>"int",
        ]);
        $state = new State;
        $state->name = $request->name;
        $state->status = $request->status;
        $state->country = $request->country;
        $state->save();
        return redirect()->route('state.show',[$state->id])->with(['status'=>"New State for $state->Country Created"]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\State  $state
     * @return \Illuminate\Http\Response
     */
    public function show(State $state)
    {
        return view("resources.states.show",["state"=>$state]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\State  $state
     * @return \Illuminate\Http\Response
     */
    public function edit(State $state)
    {
        $countries = Country::all();
        return view("resources.states.edit",["state"=>$state,"countries"=>$countries]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\State  $state
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, State $state)
    {
        $request->validate([
            "name"=>"required",
            "country"=>"int|required",
            "status"=>"int",
        ]);
        $state->name = $request->name;
        $state->status = $request->status;
        $state->country = $request->country;
        $state->save();
        return redirect()->route('state.show',[$state->id])->with(['status'=>"Updated $state->name"]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\State  $state
     * @return \Illuminate\Http\Response
     */
    public function destroy(State $state)
    {
        $state->delete();
        return redirect()->route('state.index')->with(['status'=>"State Deleted"]);
    }
}

resources/views/resources/states/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="jumbotron">
        <h3>Create new State</h3>
        <a href="{{route('state.index')}}" class="float-right btn btn-danger">Back</a>
    </div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-6">
                <div class="card">
                    <div class="card-body">
                        <form action="{{route('state.store')}}" method="post">
                            @csrf
                            <div class="form-group">
                                <label for="precise_state_name">Name</label>
                                <input type="text" name="name" id="precise_state_name" class="form-control" value="{{old('name')}}">
                            </div>
                            <div class="form-group">
                                <label for="precise_status">Status</label>
                                <select name="status" id="precise_status" class="form-control">
                                    <option @if(old('status') == '1') selected @endif value="1">Active</option>
                                    <option @if(old('status') == '0') selected @endif value="0">InActive</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="precise_country">Status</label>
                                <select name="country" id="precise_country" class="form-control" required>
                                        <option selected disabled value="0">-- Select Country --</option>
                                        @forelse ($countries as $country)
                                        <option @if(old('country') == '{{$country->id}}') selected @endif value="{{$country->id}}">{{$country->name}}</option>
                                    @empty
                                        <option selected disabled value="0">--No Countries Available --</option>
                                    @endforelse
                                </select>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-success">Save</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/resources/states/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="jumbotron">
        <h3>Edit {{$state->name}}</h3>
        <a href="{{route('state.show',[$state->id])}}" class="float-right btn btn-danger">Cancel</a>
    </div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-6">
                <div class="card">
                    <div class="card-body">
                        <form action="{{route('state.update',[$state->id])}}" method="post">
                            @csrf
                            <input type="hidden" name="_method" value="PUT">
                            <div class="form-group">
                                <label for="precise_state_name">Name</label>
                                <input type="text" name="name" id="precise_state_name" class="form-control" value="@if(old('name')) {{old('name')}} @else {{$state->name}}  @endif">
                            </div>
                            <div class="form-group">
                                <label for="precise_status">Status</label>
                                <select name="status" id="precise_status" class="form-control">
                                    <option @if(old('status') == '1' || $state->status == '1') selected @endif value="1">Active</option>
                                    <option @if(old('status') == '0' || $state->status == '0') selected @endif value="0">InActive</option>
                                </select>
                            </div>
                            <div class="form-group">
                                    <label for="precise_country">Status</label>
                                    <select name="country" id="precise_country" class="form-control" required>
                                            <option selected disabled value="0">-- Select Country --</option>
                                            @forelse ($countries as $country)
                                            <option @if(old('state') == $country->id || $state->country == $country->id ) selected @endif value="{{$country->id}}">{{$country->name}}</option>
                                        @empty
                                            <option selected disabled value="0">--No Countries Available --</option>
                                        @endforelse
                                    </select>
                                </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-success">Save</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/resources/states/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="jumbotron">
        <h3>States</h3>
        <a href="{{route('state.create')}}" class="float-right btn btn-info">Create</a>
    </div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-6">
                <div class="card">
                    <table class="table table-sm">
                        <thead class="table-dark">
                            <tr>
                                <th>State</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                           @forelse ($states as $state)
                               <tr>
                                   <th><a href="{{route('state.show',[$state->id])}}">{{$state->name}}</a></th>
                                   <th>{!!$state->Status()!!}</th>
                               </tr>
                           @empty
                               <th class="text-center" colspan="2">
                                   No states Listed
                               </th>
                           @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/resources/states/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="jumbotron">
        <h3>{{$state->name}}</h3>
        {!!$state->Status()!!}
        <div class="float-right btn-group">
            <a href="{{route('state.index')}}" class="btn btn-sm btn-danger">Back</a>
            <a href="{{route('state.edit',[$state->id])}}" class="btn btn-sm btn-outline-info">Edit</a>
            <form action="{{route('state.destroy',[$state->id])}}" method="post">
                @csrf
                <input type="hidden" name="_method" value="DELETE">
                <button type="submit" class="btn btn-sm btn-outline-danger">Delete</button>
            </form>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-4">
                <table class="table table-sm">
                    <thead class="table-dark">
                        <tr>
                            <th>city</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                       @forelse ($state->Cities as $city)
                           <tr>
                               <th><a href="{{route('city.show',[$city->id])}}">{{$city->name}}</a></th>
                               <th>{!!$city->Status()!!}</th>
                           </tr>
                       @empty
                           <th class="text-center" colspan="2">
                               No cities Listed
                           </th>
                       @endforelse
                    </tbody>
                </table>                
            </div>
        </div>
    </div>
@endsection