routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');
Route::prefix('resource')->group(function () {
    Route::resource('country', 'CountryController');
    Route::resource('state', 'StateController');
    Route::resource('city', 'CityController');
    Route::resource('campus', 'CampusController');
    Route::resource('building', 'BuildingController');
    Route::resource('zone', 'ZoneController');
    Route::resource('area', 'AreaController');
    Route::resource('room', 'RoomController');
    Route::resource('seat', 'SeatController');
});
Auth::routes();

app/City.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    public function Status()
    {
        switch ($this->status) {
            case '1':
                $status = "<span class=\"badge badge-success\">Active</span>";
                break;
            case '0':
                $status = "<span class=\"badge badge-danger\">InActive</span>";
                break;
            default:
                $status = "<span class=\"badge badge-warning\">Unknown</span>";
                break;
        }
        return $status;
    }
    public function State()
    {
        return $this->belongsTo('App\State', 'state', 'id');
    }
    
}

app/Http/Controllers/CityController.php
<?php

namespace App\Http\Controllers;

use App\City;
use App\State;
use App\Country;
use Illuminate\Http\Request;

class CityController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cities = City::paginate(10);
        return view("resources.cities.index",['cities'=>$cities]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $countries = Country::all();
        return view("resources.cities.create",["countries"=>$countries]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            "name"=>"required",
            "state"=>"int|required",
            "status"=>"int",
        ]);
        $city = new City;
        $city->name = $request->name;
        $city->status = $request->status;
        $city->state = $request->state;
        $city->save();
        return redirect()->route('city.show',[$city->id])->with(['status'=>"New City for $city->State Created"]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function show(City $city)
    {
        return view("resources.cities.show",["city"=>$city]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function edit(City $city)
    {
        $countries = Country::all();
        return view("resources.cities.edit",["countries"=>$countries,"city"=>$city]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, City $city)
    {
        $request->validate([
            "name"=>"required",
            "state"=>"int|required",
            "status"=>"int",
        ]);
        $city->name = $request->name;
        $city->status = $request->status;
        $city->state = $request->state;
        $city->save();
        return redirect()->route('city.show',[$city->id])->with(['status'=>"$city->name Updated"]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function destroy(City $city)
    {
        $city->delete();
        return redirect()->route('city.index')->with(['status'=>"Deleted"]);
    }
}

resources/views/resources/cities/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="jumbotron">
        <h3>Create new city</h3>
        <a href="{{route('city.index')}}" class="float-right btn btn-danger">Back</a>
    </div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-6">
                <div class="card">
                    <div class="card-body">
                        <form action="{{route('city.store')}}" method="post">
                            @csrf
                            <div class="form-group">
                                <label for="precise_city_name">Name</label>
                                <input type="text" name="name" id="precise_city_name" class="form-control" value="{{old('name')}}">
                            </div>
                            <div class="form-group">
                                <label for="precise_status">Status</label>
                                <select name="status" id="precise_status" class="form-control">
                                    <option @if(old('status') == '1') selected @endif value="1">Active</option>
                                    <option @if(old('status') == '0') selected @endif value="0">InActive</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="precise_state">Status</label>
                                <select name="state" id="precise_state" class="form-control" required>
                                        <option selected disabled value="0">-- Select state --</option>
                                        @forelse ($countries as $country)
                                        <optgroup label="{{$country->name}}">
                                            @forelse ($country->States as $state)
                                                <option @if(old('state') == '{{$state->id}}') selected @endif value="{{$state->id}}">{{$state->name}}</option>
                                            @empty
                                            @endforelse
                                        </optgroup>
                                        @empty
                                        <option selected disabled value="0">--No states Available --</option>
                                    @endforelse
                                </select>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-success">Save</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/resources/cities/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="jumbotron">
        <h3>Edit {{$city->name}}</h3>
        <a href="{{route('city.show',[$city->id])}}" class="float-right btn btn-danger">Cancel</a>
    </div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-6">
                <div class="card">
                    <div class="card-body">
                        <form action="{{route('city.update',[$city->id])}}" method="post">
                            @csrf
                            <input type="hidden" name="_method" value="PUT">
                            <div class="form-group">
                                <label for="precise_city_name">Name</label>
                                <input type="text" name="name" id="precise_city_name" class="form-control" value="@if(old('name')) {{old('name')}} @else {{$city->name}}  @endif">
                            </div>
                            <div class="form-group">
                                <label for="precise_status">Status</label>
                                <select name="status" id="precise_status" class="form-control">
                                    <option @if(old('status') == '1' || $city->status == '1') selected @endif value="1">Active</option>
                                    <option @if(old('status') == '0' || $city->status == '0') selected @endif value="0">InActive</option>
                                </select>
                            </div>
                            <div class="form-group">
                                    <label for="precise_state">State</label>
                                    <select name="state" id="precise_state" class="form-control" required>
                                            <option selected disabled value="0">-- Select state --</option>
                                            @forelse ($countries as $country)
                                            <optgroup label="{{$country->name}}">
                                                @forelse ($country->States as $state)
                                                    <option @if(old('state') == $state->id || $city->state == $state->id) selected @endif value="{{$state->id}}">{{$state->name}}</option>
                                                @empty
                                                @endforelse
                                            </optgroup>
                                            @empty
                                            <option selected disabled value="0">--No states Available --</option>
                                        @endforelse
                                    </select>
                                </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-success">Save</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/resources/cities/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="jumbotron">
        <h3>Cities</h3>
        <a href="{{route('city.create')}}" class="float-right btn btn-info">Create</a>
    </div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-6">
                <div class="card">
                    <table class="table table-sm">
                        <thead class="table-dark">
                            <tr>
                                <th>city</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                           @forelse ($cities as $city)
                               <tr>
                                   <th><a href="{{route('city.show',[$city->id])}}">{{$city->name}}</a></th>
                                   <th>{!!$city->Status()!!}</th>
                               </tr>
                           @empty
                               <th class="text-center" colspan="2">
                                   No cities Listed
                               </th>
                           @endforelse
                        </tbody>
                    </table>
                    <div class="card-footer">
                        {{$cities->links()}}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/resources/cities/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="jumbotron">
        <h3>{{$city->name}}</h3>
        <small>{{$city->State->name}}, {{$city->State->Country->name}}</small><br>
        {!!$city->Status()!!}
        <div class="float-right btn-group">
            <a href="{{route('city.index')}}" class="btn btn-sm btn-danger">Back</a>
            <a href="{{route('city.edit',[$city->id])}}" class="btn btn-sm btn-outline-info">Edit</a>
            <form action="{{route('city.destroy',[$city->id])}}" method="post">
                @csrf
                <input type="hidden" name="_method" value="DELETE">
                <button type="submit" class="btn btn-sm btn-outline-danger">Delete</button>
            </form>
        </div>
    </div>
    </div>
@endsection